# see CONTRIBUTING.md
---
version: '3'
services:
  proxysql:
    image: ${PROXYSQL_IMAGE:-percona/proxysql:latest}
    environment:
      # those environment variables are not actually required by ProxySQL, but entrypoint erroneously checks them
      - CLUSTER_NAME=dummy
      - DISCOVERY_SERVICE=dummy
    ports:
      - 127.0.0.1:13306:3306  # user interface
      - 127.0.0.1:16032:6032  # admin interface
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=monitor
      - MYSQL_PASSWORD=monitor
    # ports:
    #   - 127.0.0.1:23306:3306
  percona-server:
    image: percona/percona-server:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=monitor
      - MYSQL_PASSWORD=monitor
    # ports:
    #   - 127.0.0.1:33306:3306
